# Generated by Django 4.1 on 2022-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bool',
            field=models.BooleanField(default=True),
        ),
    ]
