# Generated by Django 4.1 on 2022-08-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bool',
        ),
    ]
